[package]
name = "dep-tree"
description = "Dependency tree structure for building dependency requirements"
authors = ["Dimitriy \"ay0ks\" <ay0o0ks000@gmail.com>"]
version = "0.1.0"
license = "MIT"
readme = "README.md"
edition = "2021"

[dependencies]
thiserror = "2.0.3"